<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PKMC2016" name="Login Test" tests="3" failures="1" timestamp="24 Feb 2017 15:39:07 GMT" time="74.181" errors="0">
  <testcase name="loginTest" time="37.118" classname="com.qtpselenium.core.hybrid.sessionsuite.LoginTest"/>
  <testcase name="loginTest" time="34.884" classname="com.qtpselenium.core.hybrid.sessionsuite.LoginTest">
    <failure type="java.lang.AssertionError" message="Failed - Got actual result as FAIL">
      <![CDATA[java.lang.AssertionError: Failed - Got actual result as FAIL
	at org.junit.Assert.fail(Assert.java:88)
	at com.qtpselenium.core.hybrid.Keywords.executeKeywords(Keywords.java:88)
	at com.qtpselenium.core.hybrid.sessionsuite.LoginTest.loginTest(LoginTest.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.001" classname="com.qtpselenium.core.hybrid.sessionsuite.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Login Test -->
