<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PKMC2016" name="com.qtpselenium.core.hybrid.dbsuite.DBLoginTest" tests="3" failures="1" timestamp="14 Mar 2017 21:16:38 GMT" time="43.739" errors="0">
  <testcase name="loginTest" time="20.765" classname="com.qtpselenium.core.hybrid.dbsuite.DBLoginTest">
    <failure type="java.lang.AssertionError" message="Failure in Element Extraction - dblogout_xpath">
      <![CDATA[java.lang.AssertionError: Failure in Element Extraction - dblogout_xpath
	at org.testng.Assert.fail(Assert.java:94)
	at com.qtpselenium.core.hybrid.GenericKeywords.getElement(GenericKeywords.java:227)
	at com.qtpselenium.core.hybrid.GenericKeywords.verifyText(GenericKeywords.java:174)
	at com.qtpselenium.core.hybrid.AppKeywords.verifyDBLogin(AppKeywords.java:70)
	at com.qtpselenium.core.hybrid.Keywords.executeKeywords(Keywords.java:75)
	at com.qtpselenium.core.hybrid.dbsuite.DBLoginTest.loginTest(DBLoginTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="11.173" classname="com.qtpselenium.core.hybrid.dbsuite.DBLoginTest"/>
  <testcase name="loginTest" time="11.801" classname="com.qtpselenium.core.hybrid.dbsuite.DBLoginTest"/>
</testsuite> <!-- com.qtpselenium.core.hybrid.dbsuite.DBLoginTest -->
